### ISSUE TITLE
When will the ckpts for inp_model, noinp_model, and info_gain_model be released?

### ISSUE THREAD

**Issue by alenai97** [archiki/ReCEval#7]
Additionally, the training data used for training the no_inp model and info_gain_model is also missing. If releasing the ckpts is not feasible at this time, could you consider releasing the training data used in the experiments?

Please provide a specific date for when all the materials will be released.

**Comment by archiki** [comment]
Here is the link of [checkpoints](https://drive.google.com/drive/folders/1qhWKqEAFAoIar3ydSUtMoh2YyYctutG6?usp=drive_link) and I have updated the README accordingly. For more details refer to Appendix A of our paper or consider using off-the-shelf LLMs to compute ReCEval metrics.
